#!/bin/bash
set -e

# Configurable
SRC_ROOT="${SRC_ROOT:=$(pwd)}"
DEFCONFIG="${DEFCONFIG:=imx6slevk_swift_defconfig}"
BUILDROOT_DIR="${BUILDROOT_DIR:=/workspaces/buildroot}"
SWIFT_NATIVE_TOOLS="${SWIFT_NATIVE_TOOLS:=/workspaces/swift/usr/bin}"
SWIFT_LLVM_DIR="${SWIFT_LLVM_DIR:=/workspaces/llvm}"

# Modify defconfig
DEFCONFIG_FILE=$SRC_ROOT/configs/$DEFCONFIG
DEFCONFIG_FILE_COPY=$SRC_ROOT/configs/tmp_$DEFCONFIG
cp -rf $DEFCONFIG_FILE $DEFCONFIG_FILE_COPY
echo "BR2_PACKAGE_SWIFT_HELLO=y" >> $DEFCONFIG_FILE_COPY
echo "BR2_PACKAGE_SWIFT_NATIVE_TOOLS=\"${SWIFT_NATIVE_TOOLS}\"" >> $DEFCONFIG_FILE_COPY
echo "BR2_PACKAGE_SWIFT_LLVM_DIR=\"${SWIFT_LLVM_DIR}\"" >> $DEFCONFIG_FILE_COPY

# Build
cd $BUILDROOT_DIR
make BR2_EXTERNAL=$SRC_ROOT tmp_$DEFCONFIG
rm -rf $DEFCONFIG_FILE_COPY
make source
make
