#!/usr/bin/env bash
set -e

# Configurable
SRC_ROOT="${SRC_ROOT:=$(pwd)}"
DEFCONFIG="${DEFCONFIG:=imx6slevk_swift_defconfig}"

# Modify defconfig
DEFCONFIG_FILE=$SRC_ROOT/configs/$DEFCONFIG
DEFCONFIG_FILE_COPY=$SRC_ROOT/configs/tmp_$DEFCONFIG
cp -rf $DEFCONFIG_FILE $DEFCONFIG_FILE_COPY
echo "BR2_PACKAGE_SWIFT_NATIVE_TOOLS=$SWIFT_NATIVE_TOOLS" >> $DEFCONFIG_FILE_COPY
echo "BR2_PACKAGE_SWIFT_NATIVE_TOOLS=$SWIFT_NATIVE_TOOLS" >> $DEFCONFIG_FILE_COPY

# Build
cd $BUILDROOT_DIR
make BR2_EXTERNAL=$SRC_ROOT $DEFCONFIG
rm -rf $DEFCONFIG_FILE_COPY
make
