#!/bin/bash
set -e

# Configurable
SWIFT_BUILDROOT="${SWIFT_BUILDROOT:=$(pwd)}"
DEFCONFIG="${DEFCONFIG:=imx6slevk_swift_defconfig}"
BUILDROOT_DIR="${BUILDROOT_DIR:=/workspaces/buildroot}"
SWIFT_NATIVE_TOOLS="${SWIFT_NATIVE_TOOLS:=/workspaces/swift/usr/bin}"
SWIFT_LLVM_DIR="${SWIFT_LLVM_DIR:=/workspaces/llvm}"

# Modify defconfig
DEFCONFIG_FILE=$SWIFT_BUILDROOT/configs/$DEFCONFIG
DEFCONFIG_FILE_COPY=$SWIFT_BUILDROOT/configs/tmp_$DEFCONFIG
cp -rf $DEFCONFIG_FILE $DEFCONFIG_FILE_COPY
echo "BR2_PACKAGE_SWIFT_NATIVE_TOOLS=\"${SWIFT_NATIVE_TOOLS}\"" >> $DEFCONFIG_FILE_COPY
echo "BR2_PACKAGE_SWIFT_LLVM_DIR=\"${SWIFT_LLVM_DIR}\"" >> $DEFCONFIG_FILE_COPY

# Build
cd $BUILDROOT_DIR
make BR2_EXTERNAL=$SWIFT_BUILDROOT tmp_$DEFCONFIG
rm -rf $DEFCONFIG_FILE_COPY