### Swift Collections (Collections)
SWIFT_COLLECTIONS_VERSION = 1.1.6
SWIFT_COLLECTIONS_SITE = $(call github,apple,swift-collections,$(SWIFT_COLLECTIONS_VERSION))
SWIFT_COLLECTIONS_LICENSE = Apache-2.0
SWIFT_COLLECTIONS_LICENSE_FILES = LICENSE.txt
SWIFT_COLLECTIONS_INSTALL_STAGING = YES
SWIFT_COLLECTIONS_INSTALL_TARGET = YES
SWIFT_COLLECTIONS_SUPPORTS_IN_SOURCE_BUILD = NO
SWIFT_COLLECTIONS_DEPENDENCIES = swift

SWIFT_COLLECTIONS_BUILDDIR = $(SWIFT_COLLECTIONS_SRCDIR)/build

SWIFT_COLLECTIONS_CONF_OPTS += \
	-DCMAKE_SYSTEM_NAME=Linux \
	-DCMAKE_SYSTEM_PROCESSOR=$(SWIFT_CMAKE_PROCESSOR) \
	-DCMAKE_Swift_FLAGS=${SWIFTC_FLAGS} \
	-DCMAKE_Swift_FLAGS_DEBUG="" \
	-DCMAKE_Swift_FLAGS_RELEASE="" \
	-DCMAKE_Swift_FLAGS_RELWITHDEBINFO="" \

define SWIFT_COLLECTIONS_CONFIGURE_CMDS
	(mkdir -p $(SWIFT_COLLECTIONS_BUILDDIR) && \
	cd $(SWIFT_COLLECTIONS_BUILDDIR) && \
	rm -f CMakeCache.txt && \
	PATH=$(BR_PATH):$(SWIFT_NATIVE_PATH) \
	$(SWIFT_COLLECTIONS_CONF_ENV) $(BR2_CMAKE) -S $(SWIFT_COLLECTIONS_SRCDIR) -B $(SWIFT_COLLECTIONS_BUILDDIR) -G Ninja \
		-DCMAKE_INSTALL_PREFIX="/usr" \
		-DBUILD_SHARED_LIBS=ON \
		-DBUILD_TESTING=NO \
		-DCMAKE_BUILD_TYPE=$(if $(BR2_ENABLE_RUNTIME_DEBUG),Debug,Release) \
		-DCMAKE_C_COMPILER=$(SWIFT_NATIVE_PATH)/clang \
		-DCMAKE_C_FLAGS="-w -fuse-ld=lld -target $(SWIFT_TARGET_NAME) --sysroot=$(STAGING_DIR) $(SWIFT_EXTRA_FLAGS) -I$(STAGING_DIR)/usr/include -B$(STAGING_DIR)/usr/lib -B$(HOST_DIR)/lib/gcc/$(GNU_TARGET_NAME)/$(call qstrip,$(BR2_GCC_VERSION)) -L$(HOST_DIR)/lib/gcc/$(GNU_TARGET_NAME)/$(call qstrip,$(BR2_GCC_VERSION))" \
		-DCMAKE_C_LINK_FLAGS="-target $(SWIFT_TARGET_NAME) --sysroot=$(STAGING_DIR)" \
		$(SWIFT_COLLECTIONS_CONF_OPTS) \
	)
endef

define SWIFT_COLLECTIONS_BUILD_CMDS
	(cd $(SWIFT_COLLECTIONS_BUILDDIR) && ninja)
endef

# See swift-system.mk for why we hand-copy instead of `ninja install`.
define SWIFT_COLLECTIONS_INSTALL_STAGING_CMDS
	find $(SWIFT_COLLECTIONS_BUILDDIR) -name '*.so' -type f -exec cp -f {} $(STAGING_DIR)/usr/lib/swift/$(SWIFT_LIB_SUBDIR)/ \;
	find $(SWIFT_COLLECTIONS_BUILDDIR) \( -name '*.swiftmodule' -o -name '*.swiftdoc' -o -name '*.swiftsourceinfo' -o -name '*.abi.json' \) -type f -exec cp -f {} $(STAGING_DIR)/usr/lib/swift/$(SWIFT_LIB_SUBDIR)/$(SWIFT_TARGET_ARCH)/ \;
endef

define SWIFT_COLLECTIONS_INSTALL_TARGET_CMDS
	find $(SWIFT_COLLECTIONS_BUILDDIR) -name '*.so' -type f -exec cp -f {} $(TARGET_DIR)/usr/lib/ \;
endef

$(eval $(generic-package))
