#!/usr/bin/env python3
"""Generate package/swift/swift-sources.mk and the swift-source hashes.

host-swift builds the toolchain with swift's own build-script, which expects
every peer repository of the release checked out next to the swift sources.
Rather than cloning them at configure time, buildroot downloads one GitHub
archive per repository through HOST_SWIFT_EXTRA_DOWNLOADS. This script works
out which revision each archive has to be taken from, and records the pins and
their hashes.

The pins come from utils/update_checkout/update-checkout-config.json *inside
the release being built*, never from main. update-checkout reads the pinned
revision of every peer repository from the config of the swift checkout it is
run from, and "--tag" only applies to the repositories that actually carry the
tag; everything else stays on the branch the config names. Reading main's
config while building a release therefore mixes revisions the release was
never tested against. Concretely, main pins wasi-libc to wasi-sdk-31, whose
build system is CMake only, while the 6.3.3 build-script still runs
"make install" and stops with

    make[1]: *** No rule to make target 'install'.  Stop.

swift-6.3.3-RELEASE pins wasi-sdk-27, which still ships the Makefile.

The revision of each repository is therefore resolved the same way
update-checkout resolves it:

  * if the repository carries the release tag, use the tag;
  * otherwise use the revision the branch-scheme names, and if that revision
    is a branch rather than a tag, resolve it to a commit so that the pin
    stays put after the branch moves on.

Usage:

    utils/gen-swift-source-pins.py 6.3.3

Pass --cache-dir to keep the downloaded archives around between runs, and
--config to read the update-checkout config from a local swift checkout
instead of fetching it from GitHub.
"""

import argparse
import hashlib
import json
import os
import re
import subprocess
import sys
import tarfile
import tempfile
import urllib.request

REPO_ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
SOURCES_MK = os.path.join(REPO_ROOT, "package", "swift", "swift-sources.mk")
HASH_FILE = os.path.join(REPO_ROOT, "package", "swift", "swift.hash")

CONFIG_URL = (
    "https://raw.githubusercontent.com/swiftlang/swift/{tag}"
    "/utils/update_checkout/update-checkout-config.json"
)
ARCHIVE_URL = "https://github.com/{id}/archive/{ref}/{filename}"

HASH_MARKER = "# swift-source tarballs (generated by utils/gen-swift-source-pins.py)"


def log(message):
    print(message, file=sys.stderr)


def read_config(tag, path):
    if path:
        with open(path) as handle:
            return json.load(handle)
    with urllib.request.urlopen(CONFIG_URL.format(tag=tag)) as response:
        return json.load(response)


def ls_remote(repo_id, pattern):
    """Return the refs of <repo_id> matching <pattern>, as {ref: commit}."""
    url = "https://github.com/{0}.git".format(repo_id)
    output = subprocess.run(
        ["git", "ls-remote", url, pattern],
        check=True,
        stdout=subprocess.PIPE,
        env=dict(os.environ, GIT_TERMINAL_PROMPT="0"),
    ).stdout.decode()
    refs = {}
    for line in output.splitlines():
        commit, ref = line.split("\t")
        refs[ref] = commit
    return refs


def resolve_ref(repo_id, scheme_ref, tag):
    """Resolve the revision to fetch, the way update-checkout resolves it."""
    if ls_remote(repo_id, "refs/tags/" + tag):
        return tag
    refs = ls_remote(repo_id, scheme_ref)
    if "refs/tags/" + scheme_ref in refs:
        return scheme_ref
    if "refs/heads/" + scheme_ref in refs:
        # A branch keeps moving, so record where it points today.
        return refs["refs/heads/" + scheme_ref]
    if re.fullmatch(r"[0-9a-f]{40}", scheme_ref):
        return scheme_ref
    raise RuntimeError(
        "{0}: cannot resolve '{1}' to a tag, a branch or a commit".format(
            repo_id, scheme_ref
        )
    )


def download(url, path):
    if os.path.exists(path):
        return
    log("  fetching {0}".format(url))
    os.makedirs(os.path.dirname(path), exist_ok=True)
    with urllib.request.urlopen(url) as response:
        with open(path + ".tmp", "wb") as handle:
            while True:
                chunk = response.read(1 << 20)
                if not chunk:
                    break
                handle.write(chunk)
    os.rename(path + ".tmp", path)


def sha256(path):
    digest = hashlib.sha256()
    with open(path, "rb") as handle:
        for chunk in iter(lambda: handle.read(1 << 20), b""):
            digest.update(chunk)
    return digest.hexdigest()


def submodules(path):
    """List the submodule paths declared by an archive.

    A GitHub archive carries .gitmodules but not the submodules themselves, so
    a repository that needs one to build cannot be fetched this way. Several
    repositories carry an empty .gitmodules, hence looking at the contents
    rather than at the file's presence.
    """
    with tarfile.open(path) as archive:
        for member in archive:
            parts = member.name.split("/")
            if len(parts) == 2 and parts[1] == ".gitmodules":
                content = archive.extractfile(member).read().decode()
                return re.findall(r"^\s*path\s*=\s*(\S+)", content, re.MULTILINE)
    return []


def generate(version, config_path, cache_dir):
    tag = "swift-{0}-RELEASE".format(version)
    config = read_config(tag, config_path)

    scheme = None
    for name, candidate in config["branch-schemes"].items():
        if tag in candidate.get("aliases", []) or name == "release/{0}".format(
            ".".join(version.split(".")[:2])
        ):
            scheme = candidate
            break
    if scheme is None:
        raise RuntimeError("no branch-scheme for {0}".format(tag))

    entries = []
    submodule_repos = []
    for directory, scheme_ref in scheme["repos"].items():
        if directory == "swift":
            # The swift sources are the host-swift package's own tarball.
            continue
        repo_id = config["repos"][directory]["remote"]["id"]
        log("{0}".format(directory))
        ref = resolve_ref(repo_id, scheme_ref, tag)
        filename = "swift-source-{0}-{1}.tar.gz".format(directory, version)
        path = os.path.join(cache_dir, filename)
        download(ARCHIVE_URL.format(id=repo_id, ref=ref, filename=filename), path)
        for submodule in submodules(path):
            submodule_repos.append("{0}/{1}".format(directory, submodule))
        entries.append(
            {
                "dir": directory,
                "id": repo_id,
                "ref": ref,
                "file": filename,
                "hash": sha256(path),
            }
        )

    entries.sort(key=lambda entry: entry["dir"])
    write_sources_mk(version, tag, entries)
    write_hashes(entries)

    if submodule_repos:
        log("")
        log("WARNING: these submodules are declared but not carried by the")
        log("archives. Check whether the build needs them; as of 6.3.3 the")
        log("only one is wasi-libc's copy of the WASI spec, which is used to")
        log("regenerate headers that are already checked in, not to build:")
        for entry in submodule_repos:
            log("  {0}".format(entry))


def write_sources_mk(version, tag, entries):
    lines = [
        "################################################################################",
        "#",
        "# Swift source pins",
        "#",
        "# Generated by utils/gen-swift-source-pins.py from the update-checkout",
        "# config of {0}. Do not edit by hand: rerun the script after".format(tag),
        "# changing SWIFT_VERSION.",
        "#",
        "# One entry per repository that swift's build-script expects next to the",
        "# swift sources, as <directory>|<github-id>|<revision>. The fields are",
        "# separated by a character make does not split words on, so that each",
        "# entry survives $(foreach) as one item. host-swift turns",
        "# these into HOST_SWIFT_EXTRA_DOWNLOADS so that buildroot downloads and",
        "# hash-checks them like any other source, which is what makes an offline",
        "# build possible.",
        "#",
        "# external.mk includes package/*/*.mk sorted, and '-' sorts before '.',",
        "# so this file is read before swift.mk needs SWIFT_SOURCE_REPOS.",
        "#",
        "################################################################################",
        "",
        "SWIFT_SOURCE_REPOS = \\",
    ]
    for index, entry in enumerate(entries):
        terminator = "" if index == len(entries) - 1 else " \\"
        lines.append(
            "\t{0}|{1}|{2}{3}".format(
                entry["dir"], entry["id"], entry["ref"], terminator
            )
        )
    lines += [
        "",
        "swift-repo-dir = $(word 1,$(subst |, ,$(1)))",
        "swift-repo-id = $(word 2,$(subst |, ,$(1)))",
        "swift-repo-ref = $(word 3,$(subst |, ,$(1)))",
        "swift-repo-file = swift-source-$(call swift-repo-dir,$(1))-$(SWIFT_VERSION).tar.gz",
        "",
        "# GitHub ignores everything after the revision, so naming the file here is",
        "# what keeps the downloads apart in dl/swift/.",
        "swift-repo-url = https://github.com/$(call swift-repo-id,$(1))/archive/$(call swift-repo-ref,$(1))/$(call swift-repo-file,$(1))",
        "",
    ]
    with open(SOURCES_MK, "w") as handle:
        handle.write("\n".join(lines))
    log("wrote {0} ({1} repositories)".format(SOURCES_MK, len(entries)))


def write_hashes(entries):
    with open(HASH_FILE) as handle:
        existing = handle.read()
    head = existing.split(HASH_MARKER)[0].rstrip("\n")
    lines = [head, "", HASH_MARKER]
    for entry in entries:
        lines.append("sha256 {0} {1}".format(entry["hash"], entry["file"]))
    with open(HASH_FILE, "w") as handle:
        handle.write("\n".join(lines) + "\n")
    log("wrote {0}".format(HASH_FILE))


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("version", help="Swift release, e.g. 6.3.3")
    parser.add_argument("--config", help="local update-checkout-config.json")
    parser.add_argument("--cache-dir", help="where to keep the downloaded archives")
    args = parser.parse_args()

    if args.cache_dir:
        os.makedirs(args.cache_dir, exist_ok=True)
        generate(args.version, args.config, args.cache_dir)
    else:
        with tempfile.TemporaryDirectory() as cache_dir:
            generate(args.version, args.config, cache_dir)


if __name__ == "__main__":
    main()
