################################################################################
#
# Swift source pins
#
# Generated by utils/gen-swift-source-pins.py from the update-checkout
# config of swift-6.3.3-RELEASE. Do not edit by hand: rerun the script after
# changing SWIFT_VERSION.
#
# One entry per repository that swift's build-script expects next to the
# swift sources, as <directory>|<github-id>|<revision>. The fields are
# separated by a character make does not split words on, so that each
# entry survives $(foreach) as one item. host-swift turns
# these into HOST_SWIFT_EXTRA_DOWNLOADS so that buildroot downloads and
# hash-checks them like any other source, which is what makes an offline
# build possible.
#
# external.mk includes package/*/*.mk sorted, and '-' sorts before '.',
# so this file is read before swift.mk needs SWIFT_SOURCE_REPOS.
#
################################################################################

SWIFT_SOURCE_REPOS = \
	brotli|google/brotli|v1.1.0 \
	cmake|KitWare/CMake|v3.30.2 \
	cmark|swiftlang/swift-cmark|swift-6.3.3-RELEASE \
	curl|curl/curl|curl-8_9_1 \
	indexstore-db|swiftlang/indexstore-db|swift-6.3.3-RELEASE \
	libxml2|gnome/libxml2|v2.11.5 \
	llbuild|swiftlang/swift-llbuild|swift-6.3.3-RELEASE \
	llvm-project|swiftlang/llvm-project|swift-6.3.3-RELEASE \
	mimalloc|microsoft/mimalloc|v3.0.3 \
	ninja|ninja-build/ninja|v1.13.1 \
	sourcekit-lsp|swiftlang/sourcekit-lsp|swift-6.3.3-RELEASE \
	swift-argument-parser|apple/swift-argument-parser|1.6.1 \
	swift-asn1|apple/swift-asn1|1.3.2 \
	swift-async-algorithms|apple/swift-async-algorithms|1.0.1 \
	swift-atomics|apple/swift-atomics|1.2.0 \
	swift-build|swiftlang/swift-build|swift-6.3.3-RELEASE \
	swift-certificates|apple/swift-certificates|1.10.1 \
	swift-collections|apple/swift-collections|1.1.6 \
	swift-corelibs-blocksruntime|swiftlang/swift-corelibs-blocksruntime|swift-6.3.3-RELEASE \
	swift-corelibs-foundation|swiftlang/swift-corelibs-foundation|swift-6.3.3-RELEASE \
	swift-corelibs-libdispatch|swiftlang/swift-corelibs-libdispatch|swift-6.3.3-RELEASE \
	swift-corelibs-xctest|swiftlang/swift-corelibs-xctest|swift-6.3.3-RELEASE \
	swift-crypto|apple/swift-crypto|3.12.5 \
	swift-docc|swiftlang/swift-docc|swift-6.3.3-RELEASE \
	swift-docc-render-artifact|swiftlang/swift-docc-render-artifact|swift-6.3.3-RELEASE \
	swift-docc-symbolkit|swiftlang/swift-docc-symbolkit|swift-6.3.3-RELEASE \
	swift-driver|swiftlang/swift-driver|swift-6.3.3-RELEASE \
	swift-experimental-string-processing|swiftlang/swift-experimental-string-processing|swift-6.3.3-RELEASE \
	swift-format|swiftlang/swift-format|swift-6.3.3-RELEASE \
	swift-foundation|swiftlang/swift-foundation|swift-6.3.3-RELEASE \
	swift-foundation-icu|swiftlang/swift-foundation-icu|swift-6.3.3-RELEASE \
	swift-installer-scripts|swiftlang/swift-installer-scripts|swift-6.3.3-RELEASE \
	swift-integration-tests|swiftlang/swift-integration-tests|swift-6.3.3-RELEASE \
	swift-llvm-bindings|swiftlang/swift-llvm-bindings|swift-6.3.3-RELEASE \
	swift-lmdb|swiftlang/swift-lmdb|swift-6.3.3-RELEASE \
	swift-log|apple/swift-log|1.5.4 \
	swift-markdown|swiftlang/swift-markdown|swift-6.3.3-RELEASE \
	swift-nio|apple/swift-nio|2.65.0 \
	swift-numerics|apple/swift-numerics|1.0.2 \
	swift-sdk-generator|swiftlang/swift-sdk-generator|swift-6.3.3-RELEASE \
	swift-stress-tester|swiftlang/swift-stress-tester|swift-6.3.3-RELEASE \
	swift-subprocess|swiftlang/swift-subprocess|0.2.1 \
	swift-syntax|swiftlang/swift-syntax|swift-6.3.3-RELEASE \
	swift-system|apple/swift-system|1.5.0 \
	swift-testing|swiftlang/swift-testing|swift-6.3.3-RELEASE \
	swift-toolchain-sqlite|swiftlang/swift-toolchain-sqlite|1.0.7 \
	swift-tools-protocols|swiftlang/swift-tools-protocols|0.0.9 \
	swift-tools-support-core|swiftlang/swift-tools-support-core|swift-6.3.3-RELEASE \
	swift-xcode-playground-support|apple/swift-xcode-playground-support|swift-6.3.3-RELEASE \
	swiftpm|swiftlang/swift-package-manager|swift-6.3.3-RELEASE \
	wasi-libc|WebAssembly/wasi-libc|wasi-sdk-27 \
	wasmkit|swiftwasm/WasmKit|0.1.6 \
	zlib|madler/zlib|v1.3.1

swift-repo-dir = $(word 1,$(subst |, ,$(1)))
swift-repo-id = $(word 2,$(subst |, ,$(1)))
swift-repo-ref = $(word 3,$(subst |, ,$(1)))
swift-repo-file = swift-source-$(call swift-repo-dir,$(1))-$(SWIFT_VERSION).tar.gz

# GitHub ignores everything after the revision, so naming the file here is
# what keeps the downloads apart in dl/swift/.
swift-repo-url = https://github.com/$(call swift-repo-id,$(1))/archive/$(call swift-repo-ref,$(1))/$(call swift-repo-file,$(1))
