name: Buildroot
on: [push]
jobs:
    build:
        name: Build Swift for Buildroot
        strategy:
          matrix:
            config: ["arm64", "armv7", "armv6", "armv5", "x86_64", "i386", "ppc64le"]
        runs-on: ubuntu-latest
        container: colemancda/buildroot-swift
        steps:
        - name: Checkout
          uses: actions/checkout@v3
        - name: Build
          run: |
            export SWIFT_BUILDROOT=$GITHUB_WORKSPACE
            export SWIFT_TARGET_ARCH=${{ matrix.config }}
            $SWIFT_BUILDROOT/.devcontainer/build-scripts/download-buildroot.sh
            $SWIFT_BUILDROOT/.devcontainer/build-scripts/build.sh
        - name: Archive Build artifacts
          uses: actions/upload-artifact@v3
          with:
            name: build-${{ matrix.config }}
            path: /workspaces/buildroot/output/
