name: Buildroot experimental
on: [workflow_dispatch]
jobs:

    build-ppc32:
        name: Build Swift for Buildroot (powerpc)
        strategy:
          matrix:
            config: ["qemu_ppc_mac99"]
        runs-on: ubuntu-latest
        container: swift:5.7.1-jammy
        steps:
        - name: Checkout
          uses: actions/checkout@v3
        - name: Build
          run: |
            export SRC_ROOT=$GITHUB_WORKSPACE
            export DEFCONFIG=${{ matrix.config }}_swift_defconfig
            export SWIFT_NATIVE_TOOLS=/workspaces/swift/usr/bin
            export SWIFT_LLVM_DIR=/workspaces/llvm
            export BUILDROOT_DIR=/workspaces/buildroot
            export BUILDROOT_RELEASE=2022.08.1
            export DEBIAN_FRONTEND=noninteractive 
            export DEBCONF_NONINTERACTIVE_SEEN=true
            export SWIFT_BIN_URL=https://github.com/MillerTechnologyPeru/swift/releases/download/swift-5.7.1-RELEASE/swift-5.7.1-Debian11-x86_64.tar.gz
            apt update
            $SRC_ROOT/.devcontainer/library-scripts/install-dependencies.sh
            $SRC_ROOT/.devcontainer/library-scripts/install-swift.sh
            $SRC_ROOT/.devcontainer/build-scripts/download-buildroot.sh
            cp $SRC_ROOT/package/swift/extra-patches/003-PowerPC.patch $SRC_ROOT/package/swift/003-PowerPC.patch
            $SRC_ROOT/.devcontainer/build-scripts/build.sh
        - name: Archive Build artifacts
          uses: actions/upload-artifact@v3
          with:
            name: build-${{ matrix.config }}
            path: /workspaces/buildroot/output/images

    build-mips:
        name: Build Swift for Buildroot (mips)
        strategy:
          matrix:
            config: ["qemu_mips32r6el_malta", "qemu_mips64r6el_malta"]
        runs-on: ubuntu-latest
        container: swift:5.7.1-jammy
        steps:
        - name: Checkout
          uses: actions/checkout@v3
        - name: Build
          run: |
            export SRC_ROOT=$GITHUB_WORKSPACE
            export DEFCONFIG=${{ matrix.config }}_swift_defconfig
            export SWIFT_NATIVE_TOOLS=/workspaces/swift/usr/bin
            export SWIFT_LLVM_DIR=/workspaces/llvm
            export BUILDROOT_DIR=/workspaces/buildroot
            export BUILDROOT_RELEASE=2022.08.1
            export DEBIAN_FRONTEND=noninteractive 
            export DEBCONF_NONINTERACTIVE_SEEN=true
            export SWIFT_BIN_URL=https://github.com/MillerTechnologyPeru/swift/releases/download/swift-5.7.1-RELEASE/swift-5.7.1-Debian11-x86_64.tar.gz
            apt update
            $SRC_ROOT/.devcontainer/library-scripts/install-dependencies.sh
            $SRC_ROOT/.devcontainer/library-scripts/install-swift.sh
            $SRC_ROOT/.devcontainer/build-scripts/download-buildroot.sh
            cp $SRC_ROOT/package/swift/extra-patches/004-MIPS.patch $SRC_ROOT/package/swift/004-MIPS.patch
            $SRC_ROOT/.devcontainer/build-scripts/build.sh
        - name: Archive Build artifacts
          uses: actions/upload-artifact@v3
          with:
            name: build-${{ matrix.config }}
            path: /workspaces/buildroot/output/images