name: Buildroot
on: [push]
jobs:
    build:
        name: Build Swift for Buildroot
        strategy:
          matrix:
            arch: ["arm64", "armv7", "armv6", "armv5", "x86_64", "i386", "ppc64le"]
        runs-on: ubuntu-latest
        container: colemancda/buildroot-swift:swift_${{ matrix.arch }}_defconfig
        steps:
        - name: Checkout
          uses: actions/checkout@v3
        - name: Build
          run: |
            export SWIFT_BUILDROOT=$GITHUB_WORKSPACE
            export SWIFT_TARGET_ARCH=${{ matrix.arch }}
            $SWIFT_BUILDROOT/.devcontainer/build-scripts/download-buildroot.sh
            $SWIFT_BUILDROOT/.devcontainer/build-scripts/build.sh
        - name: Archive Build artifacts
          uses: actions/upload-artifact@v4.5.0
          with:
            name: build-${{ matrix.arch }}
            path: ${{ github.workspace }}/output/${{ matrix.arch }}/images/rootfs.tar
        - name: Build Test
          run: |
              export SWIFT_BUILDROOT=$GITHUB_WORKSPACE
              export SWIFT_TARGET_ARCH=${{ matrix.arch }}
              $SWIFT_BUILDROOT/.devcontainer/build-scripts/build-test.sh
        - name: Upload test binary
          uses: actions/upload-artifact@v4.5.0
          with:
            name: swift-hello-${{ matrix.arch }}
            path: ${{ github.workspace }}/output/${{ matrix.arch }}/target/usr/bin/swift-hello
